server:
  port: 8000

spring:
  application:
    name: sgs-apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://sgs.parks.kr.s3-website.ap-northeast-2.amazonaws.com"
            allow-credentials: true
            allowedHeaders:
              - "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
      routes:
        - id: auth-server
          uri: http://3.36.146.171:8080/
          predicates:
            - Path=/auth-server/**
            - Method=POST
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: auth-server
          uri: http://3.36.146.171:8080/
          predicates:
            - Path=/auth-server/**
            - Method=GET,PUT
          filters:
            - AuthorizationHeaderFilter

token:
  secret: "qkrqudcks7"