spring:
  application:
    name: sgs-parks
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sgs-auth-server.cpzkshjlwu0y.ap-northeast-2.rds.amazonaws.com:3306/sgs-server?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: beh73167380!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'qkrqudcks7@chungbuk.ac.kr'
    password: 'beh7316!!'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
token:
  secret_key: "qkrqudcks7"
  time: 86400000
  refresh_time: 172800000

